### ISSUE TITLE
Fix usage of migrations

### ISSUE THREAD

**Issue by morrisjdev** [SapphireDb/SapphireDb#15]
The current constructor of a SapphireDbContext requires the dependency ISapphireDatabaseNotifier.
This makes it incompatible with EF Cores migration generation feature.

There can be a parameterless constructor in the SapphireDbContext class or way to get the database notifier without overriding the constructor of a DbContext.

**Comment by morrisjdev** [comment]
Resolved and will be published in version 2.2.2

**Comment by hwanders** [comment]
Nice and easy solution.

Unfortunately, since you removed the old constructor of `SapphireDbContext` this is a breaking change for all assemblies extending that class.

Perhaps adding the old constructor does not harm here and makes it downwards compatible with existing code bases (like the WebUI tests).

If the old constructor will not reappear, the README should be updated to reflect how to setup the context for unit tests (in the case where the notifier is of interest).

The reason is that the dependency is now hidden from the public API but requires configuration.

**Comment by morrisjdev** [comment]
Yes you're right. I'll readd the old constructor. Thank you for the hint.
